apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: jx-pipeline-pr
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/pullrequest.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-make-linux
          resources: {}
        # Move to catalog
        - image: golang:1.22.3-alpine3.19
          name: coverage-report
          resources: {}
          script: |
            #!/bin/sh
            . .jx/variables.sh
            apk add --update make bash curl coreutils git
            make test-coverage
            curl -s https://codecov.io/bash -o codecov.sh
            bash codecov.sh -Z -B ${PR_HEAD_REF} -C ${PULL_PULL_SHA} -f ./build/reports/cover.txt
          env:
          - name: CODECOV_TOKEN
            valueFrom:
              secretKeyRef:
                name: codecov-jx-plugins
                key: token
                optional: true
        - name: build-container-build
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h
status: {}
